### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by Shihara-Dilshan** [Shihara-Dilshan/ITP-project#6]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.6
3 info using node@v14.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle my-app@0.1.0~prestart: my-app@0.1.0
6 info lifecycle my-app@0.1.0~start: my-app@0.1.0
7 verbose lifecycle my-app@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle my-app@0.1.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/projects/ITP-project/itp-project/Front-End/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle my-app@0.1.0~start: CWD: /root/projects/ITP-project/itp-project/Front-End
10 silly lifecycle my-app@0.1.0~start: Args: [ '-c', 'react-scripts start' ]
11 silly lifecycle my-app@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle my-app@0.1.0~start: Failed to exec start script
13 verbose stack Error: my-app@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid my-app@0.1.0
15 verbose cwd /root/projects/ITP-project/itp-project/Front-End
16 verbose Linux 5.3.0-kali2-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v14.4.0
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error my-app@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the my-app@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Shihara-Dilshan** [comment]
I think you guys will get this error. when the first time you run the app it will start normally. After that it gives an error  npm ERR! code ELIFECYCLE
I found 2 solutions from stackoverflow.com 
          1. Delete node_modules folder and package.lock.json file the run npm install
          2. delete the  package.lock.json file
both solutions fix the problem for a shorter period of time.

**Comment by Shihara-Dilshan** [comment]
@ruvinwijesinghe @umesha-D 

npm create react-app my-app

Don't extract front files from the my-app folder. The package.lock.json file has a record of this directory. That's the root cause of the problem.

Don't extract front files from the my-app folder. The package.lock.json file has a record of this directory. That's the causing the problem.
